# Generated by Django 5.0.6 on 2026-06-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_site_visit_engineer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('raw_notes', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('next_follow_up_date', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
