# Generated by Django 5.0.6 on 2026-06-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('lead_score', 'Lead Score'), ('follow_up', 'Follow Up'), ('proposal', 'Proposal'), ('meeting_summary', 'Meeting Summary')], max_length=30)),
                ('provider', models.CharField(default='mock', max_length=30)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_outputs', to='leads.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
