# Generated by Django 5.0.6 on 2026-06-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('project_type', models.CharField(choices=[('residential', 'Residential House'), ('office', 'Office Interior'), ('commercial', 'Commercial'), ('renovation', 'Renovation'), ('villa', 'Villa Construction')], max_length=30)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timeline', models.CharField(choices=[('immediate', 'Immediate'), ('one_month', '1 Month'), ('three_months', '3 Months'), ('not_decided', 'Not Decided')], default='not_decided', max_length=30)),
                ('stage', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_completed', 'Site Visit Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadsource')),
                ('lost_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.lostreason')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
