# Generated by Django 5.0.6 on 2026-06-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='site_visit_engineer',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
