# Generated by Django 5.0.6 on 2026-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_site_visit_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='won_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
